webpack-contrib/style-loader

addStyles.js

Might as well apply this fix to older browsers for those of us trying to use webpack in the horrifying world of IE8

Apply default singleton to IE6-8 as well

---

url.js
useable.js

Use  loaderUtils#stringifyRequest for all

Use loaderUtils#stringifyRequest

---

README.md

Update README: set publicPath for ?sourceMap to load assets

---

useable.js

add query to style/useable like style does, ex:
```javascript
{
module: {
loaders: [
{ test: /\.css$/, exclude: /\.useable\.css$/, loader: "style?insertAt=top!css" },
{ test: /\.useable\.css$/, loader: "style/useable?insertAt=top!css" }
]
}
}
```

add query to style/useable

---

README.md

README.md update for Rule.use configuration
**Summary**
This comes from the request in https://github.com/webpack/webpack/issues/3195. @TheLarkInn forced my hand, so I had to do this. Ugh what a jerk. ;)

Change Readme to use new Rule.use configuration

---

README.md

Docs update
No
Yes
**Summary**
Wrong configuration in the example setup (#184)
No

Update README.md (#184: style-loader/usable example)

---

package.json
test/basicTest.js
test/utils.js

Unit tests
Yes
Not sure
**Summary**
Seems like I've missed that in initial commit.
#187 brought it up. Locally scoped names are provided by css-loader, it looks like style-loader just pipes them through.
No.

Unit tests for Local Scope and Local Scope + Useable

---

package.json
yarn.lock

Chore
**Summary**
Adds standard version for automatic changelog generation

chore: add standard version & script

---

test/fixUrlsTest.js

tests
no, it is tests
not required
**Summary**
Ref: https://github.com/webpack-contrib/style-loader/issues/214
no
not required

test: add inline SVG with comment test

---

README.md

Documentation fix
Not necessary
Yes
**Summary**
The field specified for webpack options was incorrect. This updates that.
No

docs(README): fix example (`options.insertInto`)

---

package-lock.json
package.json

Dependency update
No. The existing test suite is adequate.
N/A
**Summary**
This change was motivated by seeing multiple version of `schema-utils` in my project bundle.
There are no breaking changes in `schema-utils` from `0.4.5` to `1.0.0`
That's it.

chore(package): update `schema-utils` v0.4.5...1.0.0 (`dependencies`)

---

.circleci/config.yml
package-lock.json
package.json
test/basic.test.js
test/utils.js

Just update deps to future webpack-defaults update

chore(deps): update

---

lib/urls.js
package-lock.json
package.json
test/basic.test.js
test/fixUrls.test.js
test/url.test.js
test/useable.test.js
test/utils.js

refactor - migrate on jest, we still need rewrite tests, now they are very badly

refactor: migrate on jest

---

README.md

docs(README): Fix illegal semicolon in example code

---

package.json

The project will publish successfully unless **package.json** updates its references to the files it intends to publish.
No, there are no breaking changes.
Tests will fail due to the `npm ci` audit, until either #383 or #384 are merged. 😄

fix: package.json dist files required for publish

---

src/index.js
src/options.json
src/url-loader.js
src/useable-loader.js
test/__snapshots__/validate-options.test.js.snap
test/validate-options.test.js

test option for loader(s)
No
No

test: validate options

---

src/runtime/addStyles.js
test/runtime/__snapshots__/addStyle.test.js.snap
test/runtime/__snapshots__/addStyleUrl.test.js.snap
test/runtime/addStyle.test.js
test/runtime/addStyleUrl.test.js

test: unit

---

src/runtime/addStyles.js

fix: es3 compatibility

---

azure-pipelines.yml
package.json

chore: es3 linting

---

src/runtime/addStyles.js
test/runtime/__snapshots__/addStyle.test.js.snap
test/runtime/addStyle.test.js

respect `sourceMap` option
No
fixes #346

fix: respect `sourceMap` option

---

package-lock.json
package.json
src/runtime/addStyles.js
test/manual/index.html
test/manual/src/index.js
test/manual/src/other-style.scss
test/manual/src/style.css
test/manual/webpack.config.js
test/runtime/__snapshots__/addStyle.test.js.snap

manual tests
No
fix invalid source map file

chore: manual test helper

---

src/runtime/addStyles.js

refactor: code

---

package.json

chore: fix package files

---

src/runtime/addStyleUrl.js
src/runtime/addStyles.js
test/__snapshots__/attributes-option.test.js.snap
test/__snapshots__/base-option.test.js.snap
test/__snapshots__/insert-option.test.js.snap
test/__snapshots__/loader.test.js.snap
test/__snapshots__/singleton-option.test.js.snap
test/__snapshots__/sourceMap-option.test.js.snap
test/runtime/__snapshots__/addStyle.test.js.snap
test/runtime/__snapshots__/addStyleUrl.test.js.snap

It is unnecessary
Should be not
No

feat: remove type `text/css` from style and link element

---

test/manual/index.html
test/manual/src/custom-square.js
test/manual/src/custom-square.lazy.css
test/manual/src/index.js

custom element test
No
For future API

test: custom element

---

test/runtime/__snapshots__/addStyle.test.js.snap
test/runtime/addStyle.test.js

test: more

---

src/runtime/addStyleUrl.js
src/runtime/addStyles.js

refactor: remove unnecessary debug error

---

.eslintrc.js
src/runtime/injectStylesIntoLinkTag.js
src/runtime/injectStylesIntoStyleTag.js
test/helpers/compiler.js
test/loader.test.js

refactor and reduce runtime size (when you use terser)
No
No

refactor: runtime code

---

README.md

docs: note about source maps in singleton mode

---

test/manual/src/component.lazy.module.css
test/manual/src/index.js
test/manual/webpack.config.js

test: lazy css modules

---

src/index.js

regression when do refactor
No
No

refactor: restore hmr for lazy styles after refactor

---

README.md

docs: clarify linkTag

---

package-lock.json
package.json
src/index.js
src/runtime/injectStylesIntoLinkTag.js
test/loader.test.js
test/manual/src/index.js
test/manual/webpack.config.js

fix: support ES module syntax

---

test/__snapshots__/attributes-option.test.js.snap
test/__snapshots__/base-option.test.js.snap
test/__snapshots__/injectType-option.test.js.snap
test/__snapshots__/insert-option.test.js.snap
test/attributes-option.test.js
test/base-option.test.js
test/injectType-option.test.js
test/insert-option.test.js

test: refactor

---

test/manual/index.html
test/manual/src/index.js
test/manual/src/use-unuse.lazy.css

test: more manual test

---

README.md
src/index.js
src/options.json
src/runtime/isEqualLocals.js
test/__snapshots__/modules-option.test.js.snap
test/__snapshots__/validate-options.test.js.snap
test/fixtures/named-export.css
test/fixtures/named-export.js
test/manual/src/index.js
test/manual/src/style.named-export.lazy.module.css
test/manual/src/style.named-export.module.css
test/manual/webpack.config.js
test/modules-option.test.js
test/runtime/isEqualLocals.test.js
test/validate-options.test.js

feat: added `modules.namedExport`

---

package-lock.json
package.json
src/index.js

Updated schema-utils
- minimum supported Node.js version is 10.13.0
No

Chore: updated schema-utils

---

README.md
src/index.js
test/attributes-option.test.js
test/insert-option.test.js
test/loader.test.js

Enabled esModule by default
Yes
No

Feat: enabled esModule by default

---

.github/workflows/nodejs.yml

ci: fixed lint matrix setup

---

src/index.js
test/__snapshots__/esModule-option.test.js.snap
test/esModule-option.test.js

processed use case with namedExport and exportOnlyLocals
No
No

refactor: processed use case with namedExport and exportOnlyLocals

---

README.md

https://webpack.js.org/loaders/style-loader/#recommend
does not render properly

Update style-loader README.md

---

test/manual/webpack.config.js

test: update

---

README.md

Fixes #613
--
I created these additions based on https://github.com/webpack-contrib/style-loader/issues/613#issuecomment-1843225551 by @alexander-akait. I hope this is what you had in mind.

docs(security): Add warning
