webpack-contrib/style-loader

- addStyles.js
IE9 will actually drop certain things (like media queries) from the
cssText property when it is read back out. To fix, store the raw css
text in a separately managed array, and use that to form the entire
string that should be set on the style element's cssText property.
Fixes #39.
> [#39] Don't use styleSheet to store state of css text

- addStyles.js
Fixes error described here: http://stackoverflow.com/a/26603875. I can only reproduce the issue when style-loader is used together with autoprefixer-loader ^1.2.0 in this configuration:
```javascript
config.module.loaders.push({
test: /\.scss$/,
loaders: [
"style-loader",
"css-loader?sourceMap",
"autoprefixer-loader",
"sass-loader?sourceMap&sourceMapContents=true" + helpers.getScssIcludePathsAsArgs(),
],
});
```
Perhaps the issue is with autoprefixer-loader? I'm not sure how to find the root cause.
> Wrap sourceMap JSON in unescape and encodeURIComponent.

- package.json
since `stringifyRequest` was introduced in that version
> update loader-utils dependency to 0.2.7

- README.md
- addStyles.js
Implemented for #56. Adds an 'insertAt' parameter that lets you specify where you would like to insert the style tags in the head, either 'top' or 'bottom' (the default). This lets you avoid taking priority over any CSS already in the head if you so desire.
> Add support for 'insertAt' parameter

- addStyles.js
This is in response to the issue brought up by @sokra in [PR 59](https://github.com/webpack/style-loader/pull/69).
> Could you do a follow-up PR that fix this, i. e. by storing a list of all top-inserted style tags and inserting after the last one.
> Fixed ordering of stylesheets inserted with insertAt=top.

- addStyles.js
in order to fix uglifyjs warnings
```
Side effects in initialization of unused variable sourceMap [./~/style-loader/addStyles.js:185,0]
Side effects in initialization of unused variable media [./~/style-loader/addStyles.js:203,0]
```
> drop unused vars

- addStyles.js
Replacing `window` with `self` to better support web workers, they are the same thing in UI thread; https://developer.mozilla.org/en-US/docs/Web/API/Window/self.
This enables style loading in web worker context, for example by using this technique; https://github.com/web-perf/react-worker-dom/tree/r-15.
> Replace window with self for better web worker support

- README.md
Summary:
----
Webpack v2.1.0-beta.26 introduced a breaking change to require loaders to have the `-loader` suffix. 
This PR updates the README to show that pattern as an example instead of using the shorthand naming.
cc: @sokra
> Add -loader suffix to reflect new loader syntax webpack 2 requirement

- README.md
Update the link to css-loader local scope
Updated README
Yes
**Summary**
The link to local scope seems to have been outdated, so this is a fix to the new hash.
No
> Fixed link to local scope

- index.js
- package.json
- useable.js
fix deprecated warning
no
no
**Summary**
fix this
link: webpack/loader-utils#56
no
> fix deprecated warning

- addStyles.js
Although the rel element is set to stylesheet the created link element does not specify the MIME type of the linked resource.
The MIME type is set to text/css similar to the case when an style element is created. This change also syncs with the addStylesUrl.js behavior where the type attribute is set.
bugfix/enhancement
no
no
**Summary**
There are tools/frameworks that rely on MIME type for processing static content prior delivering the resources. In this particular case the href tag is not updated correctly because the type attribute is missing.
> Adds type attribute to the generated link element

- README.md
- addStyles.js
- test/basicTest.js
What kind of change does this PR introduce?
feature, allows to add additional attributes on the style / link element that the loader creates
Did you add tests for your changes?
No, tests
If relevant, did you update the README?
Update README
Summary
This PR allows to add id attribute or any custom attribute, in my case i have runtime css style processor that relies on custom attribute on the style tag that it should process.
Does this PR introduce a breaking change?
no breaking changes
Other information
Fixes #147
Related #155
> feat(tag-attribute): Add support for custom tag attribute

- .gitignore
- README.md
- addStyles.js
- fixUrls.js
- test/fixUrlsTest.js
This is rebased from bendytree (#124)
> added option to fix relative urls

- addStyles.js
a bugfix
no, but perhaps it can be fixed by introducing `eslint` to the project
no
**Summary**
`const` keyword was added in [this commit](https://github.com/webpack-contrib/style-loader/commit/19959eeb777bef4b1361501dc2ba2e4c785d63e0#diff-087146d437551cdc1e1ec8b9e39faaa3R252) and released as `0.14.0` which is causing syntax error in IE10 and below
no
> fix: syntax error in IE10 and below because of `const` keyword

- fixUrls.js
- test/fixUrlsTest.js
> Match parens recursively on URLs to not fix embeded calls

- README.md
- addStyles.js
- test/basicTest.js
- test/utils.js
Add another option called `insertInto` - which allows specifying a CSS selector - e.g. `#styles` - to be used as an argument to `document.querySelector` to find an element into which to insert the generated `<style>`-tags. Will default to the `<head>`-tag if undefined.
This was created because I wanted to insert `<style>` tags into a ShadowRoot (like in #131), but this is not a specific solution for that, but does solve it by allowing people to first create a ShadowRoot and then target it using `insertInto` and the appropriate selector.
Not att all sure if this is wanted, but it exists, so there ya go :)
Also, I replaced the `getHeadElement` function with a custom memoized function rather than add the key feature to the existing memoizing function, not sure if that was the better choice, …
> Add insertInto option

- addStyles.js
Bugfix for #177
Change is only testable in a browsers, code itself was tested using Browserstack into whole range of IE versions across all versions of Windows starting from XP and into outdated / actual versions of all browsers on Windows / OS X / Android / iOS / Windows Phone.
Doesn't seems to be relevant
**Summary**
Test for old IE versions is updated to avoid blind accessing properties of global objects that may not be available into certain real environments (examples are [here](https://github.com/webpack-contrib/style-loader/issues/177#issue-210376738) and [here](https://github.com/webpack-contrib/style-loader/issues/177#issuecomment-284250644)). Since …
> Update for test for old IE versions

- README.md
- addStyleUrl.js
- test/basicTest.js
- url.js
Feature: add ability to set custom attributes for tag in url mode.
Yes, I added tests for this PR.
No
**Motivation**
This PR related to https://github.com/webpack-contrib/style-loader/commit/995f3de. In that release introduced ability to add custom attributes to tag only for default/usable mode, but not for url mode.
My PR covered that functionality.
No
> feat: Set custom attributes for tag in url mode

- test/basicTest.js
Test cases: passing and failing
Yes, only tests.
**Summary**
Using `style-loader` and `css-loader` with local scoped identifiers and `composes` works as expected.
However when adding `css-loader`s `getLocalIdent` option, only some identifiers are properly passed through the custom `getLocalIdent`, while the identifiers from the composed files are still using the `localIdentName` option.
See the failing test `local scope, composing, custom getLocalIdent`
I submitted this PR here, because this is not reproducible when using only the `css-loader`.
> test: usage with css-loader and composes

- README.md
- addStyles.js
…loader/issues/163
bugfix / workaround for https://github.com/webpack/style-loader/issues/163
no
no
**Summary**
This is a workaround. It allows the user to manually specify base id's for each bundle when multiple bundles are used on a page. The user would for have to manually specify the order in various webpack.configs like so:
dll1.js
`loaders:[ { test: /\.css$/, loader: 'style-loader!css-loader' } ]`
dll2.js
`loaders:[ { test: /\.css$/, loader: 'style-loader?cssBase=1000!css-loader' } ]`
app.js
`loaders:[ { test: /\.css$/, loader: 'style-loader?cssBase=2000!css-loader' } ]`
see https://github.com/webpack/style-loader/issues/163
**Does this PR introduce a …
> feat: add option.base

- README.md
Fixed a typo in the example code
given in the readme
> docs(README): fix a typo in example

- README.md
A docs bugfix.
N/A
Yes.
**Summary**
README contained unescaped & unclosed `<style>` tag that made almost the whole
README unreadable on the npm package page; see:
https://www.npmjs.com/package/style-loader
No.
This is a good test page to see how READMEs will display on npm:
https://revin.github.io/marky-markdown/
> docs(readme): Fix markdown error

- README.md
A docs bugfix.
N/A
Yes.
**Summary**
PR #227 made the README not broken completely on the npm package page (https://www.npmjs.com/package/style-loader) but didn't make the code block a real code block. Backticks are only used to delimit code blocks when used on the top level of the Markdown file; once they appear in an HTML block they're treated as regular symbols. The proper fix is to use the `<code>` tag.
No.
> docs(readme): Fix the `<style>` code block

- index.js
Stringifies the request for the transform module, to support cross-platform paths. Fixes #229.
Bugfix
The current tests cover it
N/A
**Summary**
Support cross-platform paths for transform module
Solves #229
No.
> fix: stringify the options.transform request

- lib/addStyles.js
> fix(addStyles): revert merged loops

- url.js
Bugfix
✅ 
✅ 
**Summary**
Fixes #241 
No
> fix(url): use `loaderUtils.stringifyRequest` to avoid invalidating hashes due to absolute paths

- lib/addStyles.js
bugfix
Private function… no tests.
Not relevant.
**Summary**
style-loader was choking on the CSS Modules `composes` feature and throwing a fatal error. Adding a check to the `removeStyleElement` function in `lib/addStyles.js` seems to solve the problem.
No.
Closes #182
> fix: Adds null check to `removeStyleElement`

- README.md
- lib/addStyles.js
- test/basicTest.js
- add possibility to target an iframe with the `insertInto` setting
- select head in the iframes content document
- use try/catch to avoid breakting the code if permission is denied
Yes.
Yes.
**Summary**
Pull request for open issue **insertInto for iframes #213**
No.
Closes #213
> feat: add support for iframes (`options.insertInto`)

- README.md
Fix bash code example highlight.
Tests are not required.
Only README was updated.
Code text will be more accurate and nice.
---
> docs(README): fix bash code highlight

- README.md
- lib/addStyles.js
- options.json
- test/basicTest.js
Allow new styles to be inserted before other `<style>` or `<link>` elements that
exist on the page. This allows more precise ordering for complex style overrides
between multiple sources.
New feature
Yes
Yes
**Summary**
This is a new feature adding a third possible value for `insertAt`: `"before"`. A new option value `insertBefore` which contains query selector to select the element that the new styles should precede.
Complicated style situations where multiple `<style>` tags exist and must be inserted in specific order to allow style-overrides to work across sections require more precise placement than just `top` or `bottom`. This feature allows more precise …
> feat: support 'before' insertions (`options.insertAt`)

- README.md
- index.js
- lib/addStyleUrl.js
- options.json
- package.json
- test/basicTest.js
- test/urlTest.js
- test/useableTest.js
- test/utils.js
- url.js
- useable.js
- yarn.lock
- Fixes #263 
> edited by @michael-ciniawsky (Formatting && Issues)
> feat: add option to enable/disable HMR (`options.hmr`)

- README.md
documentation improvement
n/a
yes
**Summary**
Several configuration examples were missing commas in object syntax.
Form mine (and hopefully others) peace of mind
no
> fixed missing commas in configuration examples

- README.md
- lib/addStyles.js
- test/basicTest.js
bugfix
yes
yes, we don't have `singleton` option in table options, i don't know how it is happens
**Summary**
When `singleton: true` - i want to use one `style` tag.
When `singleton: false` - i want to use multiple `style` tags.
When `singleton` not specify (i.e. `undefined`) - i want the loader himself decide to use single or multiple `style` tags.
Issue: https://github.com/webpack-contrib/style-loader/issues/283
No
> fix(addStyles): correctly check `singleton` behavior when `{Boolean}` (`options.singleton`)

- lib/addStyles.js
Fix on some browser the fact that `window.HTMLIFrameElement` doesn't exist
Not relevant IHMO
Not relevant IHMO
**Summary**
Style-loader can be used with Cobalt browser (https://cobalt.foo)
No
Thank for your work
**Cobalt**
(https://cobalt.foo)
> A high-performance, small-footprint platform that implements a subset of HTML5/CSS/JS to run applications, including the YouTube TV app.
I had some trouble to connect in https on their website with chrom{ium, e} but not with firefox
> fix(addStyles): check if `HTMLIFrameElement` exist

- index.js
chore
none needed
not relevant
**Summary**
Removed trailing whitespace, fixed indentation (some lines had spaces instead of tabs like all other lines).
https://github.com/webpack-contrib/style-loader/commit/be51e32c4c81dca148426e6262694928dfdc5af5#r27136994
nope
> fix(index): source code indentation

- README.md
> docs(README): escape `|` character in options table

- lib/urls.js
- test/fixUrls.test.js
bugfix
yes
don't need
**Summary**
Ref: https://github.com/webpack-contrib/css-loader/issues/462
no
> fix(urls): skip empty `url()` handling

- package-lock.json
- package.json
Dependency update
No, not necessary.
No, not necessary.
**Summary**
This PR fixes warnings with Webpack 4:
`warning "style-loader > schema-utils@0.4.3" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".`
No.
Nothing.
> fix(package): update `schema-utils` v0.4.3...0.4.5 (`dependencies`)

- lib/addStyles.js
- test/basic.test.js
Small feature
Yes.
No.
**Summary**
This lets projects using style-loader define the type of the style or link tags in the `attrs` option of the loader, along with other tag attributes. See [style-loader/issues/315](https://github.com/webpack-contrib/style-loader/issues/315)
No.
> feat: enable tag type configuration

- lib/addStyles.js
- test/basic.test.js
Bugfix
Yes, added test case too.
No need to update README.
**Summary**
When using insertInto ( as a function ) and insertAt (as an object), the compiled code would throw an error in console. In this PR, I've changed source code slightly and without affecting existing workflow. 
An issue I've raised in recent. #313 
No. Testing well. And test case also got 100 percentage result.
Hope you will accept my PR ASAP. Casue, we've a recuirement based on this.
> insertInto and insertAt collaboration bug fixed

- lib/addStyles.js
- test/basic.test.js
Feature to support `__webpack_nonce__` 
Yes, I added a test that verifies the nonce gets set on style tags. (Nonces will not help `link` tags as nonces are only used to allow inline styles.)
I wasn't sure where in the README I should put a note about supporting `__webpack_nonce__`, so I have omitted it for now. I can add it in if requested.
**Summary**
Currently if a site has a strict CSP that disallows `unsafe-inline` the rendered style tags from this loader will be ignored. Webpack supports adding a nonce via the `__webpack_nonce__` property. This change looks for that property and adds the nonce attribute to generated style tags.
More info here: #306 …
> feat(addStyles): add support for `__webpack_nonce__`

- README.md
add missing information about what useable does
**Summary**
> docs(readme): clarify `useable` usage

- lib/addStyles.js
v0.22.0 introduced support for webpack nonces, however the code contains a `const` keyword which throws on IE10 and below. This PR replaces `const` with `var` so everybody's happy. I've verified this fix in IE10.
> fix(addStyles): use `var` instead of `const` (IE fix)

- test/useable.test.js
- useable.js
feature. adds support for insertInto with `useable`. fixes #327 
Yes
I didn't, I figured this feature should be assumed to work with `useable` as well. I can add documentation to point it out though.
**Summary**
This feature is needed for injecting styles into the iframe with `useable` AFTER the page has loaded. Having the ability to call `style.use()` when the iframe is being setup is crucial. In this scenario we can't use the basic style-loader because specifying the insertInto option will attempt to look for the iframe when it doesn't exist yet.
No
n/a
> feat(useable): add `insertInto` support (`options.insertInto`)

- README.md
- lib/addStyles.js
- test/basic.test.js
- test/transforms/transform_es6.js
> fix(addStyles): support exports of transpiled transforms (`options.transform`)

- README.md
The code example does not include a `exclude` entry, which causes the loaders to load twice on ".useable.css" files and failing the build.
> Fixed `Useable` section code in README.md

- README.md
- src/options.json
- src/runtime/addStyleUrl.js
- src/runtime/addStyles.js
- test/__snapshots__/validate-options.test.js.snap
- test/loader.test.js
- test/runtime/__snapshots__/addStyle.test.js.snap
- test/runtime/__snapshots__/addStyleUrl.test.js.snap
- test/runtime/addStyle.test.js
- test/runtime/addStyleUrl.test.js
- test/validate-options.test.js
Rename `attrs` to `attributes`
Yes
BREAKING CHANGE: `attrs` options was renamed to `attributes`
No
> refactor: rename `attrs` option to `attributes`

- README.md
- src/index.js
- src/options.json
- src/runtime/addStyles.js
- test/__snapshots__/validate-options.test.js.snap
- test/loader.test.js
- test/runtime/__snapshots__/addStyle.test.js.snap
- test/runtime/addStyle.test.js
- test/transforms/false.js
- test/transforms/noop.js
- test/transforms/transform.js
- test/transforms/transform_es6.js
- test/validate-options.test.js
Remove `transform` option because this option is unsafe (may create security bugs) and increase bundle size. We recommend use `postcss-loader` to handle css (polyfilling, replacing values and etc) or create separate loader for non standard things.
Yes
BREAKING CHANGE: option `transform` was removed without replacement
No
> refactor: remove `transform` option

- README.md
- src/index.js
Remove duplicate api for reducing runtime code
Yes
BREAKING CHANGE: removed `ref`/`unref` api were removed for useable loader, please use `use`/`unuse` api
No
> refactor: removed `ref` and `unref` api for useable loader

- README.md
example for `nonce`
No
fixes #306
> docs: example for `nonce` usage

- README.md
- src/index.js
- src/options.json
- src/runtime/injectStylesIntoLinkTag.js
- src/runtime/injectStylesIntoStyleTag.js
- test/__snapshots__/insert-option.test.js.snap
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/fixtures/element.js
- test/fixtures/lazy-element.js
- test/insert-option.test.js
- test/loader.test.js
- test/runtime/__snapshots__/injectStylesIntoLinkTag.test.js.snap
- test/runtime/__snapshots__/injectStylesIntoStyleTag.test.js.snap
- test/runtime/injectStylesIntoLinkTag.test.js
- test/runtime/injectStylesIntoStyleTag.test.js
- test/validate-options.test.js
Implement `insert` option for custom insert logic
Yes
BREAKING CHANGE: `insertAt` and `insertInto` option was removed in favor `insert` option (please look docs and examples)
We still doesn't recommended use non standard behavior
> refactor: `insert` option

- src/index.js
- test/manual/webpack.config.js
fixes #320
Yes
/cc @lydell 
Here right example:
```js
if(module.hot.data) {
if(!equal(module.hot.data.locals, locals)) {
// Continue bubbling when we detect locals doesn't match
module.hot.setUnhandled();
}
}
module.hot.accept();
module.hot.dispose(data => {
data.locals = locals;
});
```
but now we don't have `module.hot.setUnhandled` api, we will try implement this for `webpack@5` (but we have many tasks), now i jest revert this PR, because it is break hot reloading in many cases (include `hot-react-loader`)
> fix: restore original hot reloading behaviour for locals

- README.md
“attributes” was misspelled a couple times. This also fixes the anchor fragment for linking to `#attributes`.
I guess this would break existing URLs that pointed to `#attirbutes`.
> Typo: attirbutes→attributes

- README.md
- package-lock.json
"Doom" might be applicable to some aspects of the DOM specifications, but I don't think this was intended as some sort of commentary.
I originally spotted the typo on: https://webpack.js.org/loaders/style-loader/
N/A
N/A
> Fixed typo 'doom' to 'DOM' in README.md

- package.json
- src/cjs.js
- src/index.js
- test/cjs.test.js
- test/helpers/getCompiler.js
- test/loader.test.js
> refactor: cjs

- src/index.js
- test/manual/webpack.config.js
for future `esModule` option
No
No
> refactor: code

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/esModule-option.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/esModule-option.test.js
- test/manual/webpack.config.js
- test/validate-options.test.js
> feat: `esModule` option

- src/runtime/injectStylesIntoStyleTag.js
- test/runtime/__snapshots__/injectStylesIntoStyleTag.test.js.snap
- test/runtime/injectStylesIntoStyleTag.test.js
fixes #447
No
Supporting non-array list of modules will be removed in next version, my recommendation is https://github.com/webpack-contrib/style-loader/issues/447#issuecomment-568685446
> fix: checking that the list of modules is an array

- src/index.js
- src/runtime/injectStylesIntoStyleTag.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/lazy-multiple.js
- test/fixtures/multiple.js
- test/fixtures/nested/style.css
- test/fixtures/other-nested/style.css
- test/loader.test.js
- test/manual/index.html
- test/manual/src/duplicate.css
- test/manual/src/index.js
- test/manual/src/nested.css
- test/manual/src/nested/style.css
- test/runtime/__snapshots__/injectStylesIntoStyleTag.test.js.snap
- test/runtime/injectStylesIntoStyleTag.test.js
fixes #445
Should be not, feel free to feedback
+ increase performance
> fix: algorithm for importing modules

- README.md
Other loaders/plugins has this in their docs. So replicated the same
N/A
N/A
> chore(docs): added link for the options table

- src/index.js
- src/runtime/isEqualLocals.js
- test/runtime/isEqualLocals.test.js
hmr for css modules
No
It is hard to write tests for hmr, so tested manually, feel free to open a new issue if you have a problems with this
fixes #422
> Feat hmr for css modules

- src/index.js
- test/esModule-option.test.js
- test/fixtures/simple.js
- test/helpers/runInJsDom.js
https://github.com/webpack-contrib/style-loader/issues/475
Nope
...
> fix: esModule option issue fix

- src/runtime/injectStylesIntoStyleTag.js
If the `btoa` function does not exist, an error will occur as follows.
```
btoa is not defined
```
> fix: check if 'btoa' exists for old IE versions

- babel.config.js
- package.json
We need to do it together with `mini-css-extract-plugin` major release, I think we will do it in the next/next next week
No
No
> revert: node bump

- README.md
https://robertknight.github.io/posts/webpack-dll-plugins/ is dead. https://robertknight.me.uk/posts/webpack-dll-plugins/ works.
> linkfix: webpack-dll-plugins

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/validate-options.test.js.snap
- test/manual/webpack.config.js
- test/modules-option.test.js
- test/validate-options.test.js
Removed `modules.namedExport` option in favor `modules.namedExport` option in [`css-loader`](https://github.com/webpack-contrib/css-loader)
Yes
No
> feat: removed modules.namedexport option

- package-lock.json
- src/index.js
- src/runtime/setAttributesWithAttributes.js
- src/runtime/setAttributesWithAttributesAndNonce.js
- src/runtime/setAttributesWithoutAttributes.js
- src/utils.js
- test/manual/src/index.js
`setAttributes` function moved in module
`test:manual` fixed
No
No
> Refactor:  setAttributes function moved in module

- src/utils.js
- test/__snapshots__/insert-option.test.js.snap
- test/insert-option.test.js
When the `insert` option is an absolute path to a function, it is added to the` buildDependencies`
No
No
> fix: insert function path added to buildDependencies

- src/utils.js
- test/__snapshots__/styleTagTransform-option.test.js.snap
- test/styleTagTransform-option.test.js
When the `styleTagTransform` option is an absolute path to a function, it is added to the` buildDependencies`
No
No
> fix: styleTagTransform function path added to buildDependencies

- README.md
- src/index.js
- src/runtime/insertStyleElement.js
- src/runtime/styleDomAPI.js
- test/fixtures/lazy-insertOptions.js
- test/lazyStyleTag-insertOptions.test.js
Allow to pass additional parameter to `style.use(anything)` which will be passed to `insert` function. This allows to insert each tag in different places and especially useful for Shadow DOM
Resolves #328
I'm using style-loader in WebExtension and we heavily rely on Shadow DOM (we inject our widgets into 3rd party sites and want them look always nice, same on all sites). But it was a pain to inject styles into Shadow DOM (you better not peek on my old webpack config haha!). This small change allows to pass custom options (any object basically) to the `styles.use` call, which later will be passed to `insert` function. This allows customizing `insert` logic: now you can insert each style into different place and do whatever you want for each style individually
This …
> feat: allow to pass options to `insert` function through `style.use()`

- src/runtime/injectStylesIntoLinkTag.js
- src/runtime/isOldIE.js
- src/runtime/singletonStyleDomAPI.js
- src/runtime/styleDomAPI.js
- test/__snapshots__/injectType-option.test.js.snap
- test/injectType-option.test.js
fixes https://github.com/webpack-contrib/style-loader/issues/595
No
Based on https://github.com/webpack-contrib/style-loader/compare/master...OlegWock:style-loader:master, but looks like we don't need to handle document here [src/runtime/insertBySelector.js](https://github.com/webpack-contrib/style-loader/compare/master...OlegWock:style-loader:master#diff-1dcb8874fcaa26075962961db1fe6dedc03bf24cf578233be979e1299086f223)
> fix: noop in environment without DOM API

- package-lock.json
- package.json
- src/index.js
- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
do nothing when built-in CSS support enabled
No
https://github.com/webpack/webpack/issues/17223
> fix: compatibility with built-in CSS support

- README.md
fixes https://github.com/webpack-contrib/style-loader/pull/452/
No
No
> docs: improve more
